### ISSUE TITLE
Colon-delimited NODE_PATH causes error

### ISSUE THREAD

**Issue by MOZGIII** [ricardobeat/require-tree#5]
From node's docs:

> If the NODE_PATH environment variable is set to a colon-delimited list of absolute paths, then node ...

But when I'm trying to launch the project that uses `required-tree` with NODE_PATH set to colon-delimited list, it fails.

```
> lets-chat@0.4.2 start /home/letstalk/app
> node app.js

fs.js:761
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript/app/models'
    at Error (native)
    at Object.fs.readdirSync (fs.js:761:18)
    at require_tree (/home/letstalk/app/node_modules/require-tree/index.js:37:24)
    at Object.<anonymous> (/home/letstalk/app/app.js:33:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

Fix plz.

**Comment by elliotf** [comment]
See #6 for fix

**Comment by ricardobeat** [comment]
f08edb3809dccce4aa6679dc0f2285130b4c4167 adds support for multiple paths in `NODE_ENV`. This is in release 1.1.0. Thanks @MOZGIII @elliotf for reporting the bug.
